##########################
Brand new to neuroimaging?
##########################

Familiarize yourself with important background reading material here. If you’re unsure about any terms, check out the `glossary <content_pages/glossary>`_.

.. toctree::
   :maxdepth: 1

   content_pages/01-01-openNeuro
   content_pages/01-02-whatIsBIDS
   content_pages/01-04-faq
   content_pages/01-05-overview

##########################
Setting up your experiment
##########################

.. toctree::
   :maxdepth: 1
   :caption: Follow these important steps before running your first subject!

   content_pages/02-01-computingWorkflow
   content_pages/02-02-designExp
   content_pages/02-03-acquisitionParams
   content_pages/02-04-reproin
   content_pages/02-05-prescan
   content_pages/02-06-forms


##########
Using BIDS
##########

.. toctree::
   :maxdepth: 1
   :caption: After running your first subject, go from raw DICOMs to preprocessed niftis. Make sure everything works before running more subjects!

   content_pages/03-01-sampleProjectWithBIDS
   content_pages/03-02-converting
   content_pages/03-03-mriqc
   content_pages/03-04-fmriprep
   content_pages/03-05-fmriprepOutputs
   content_pages/03-06-sampleProjectWithDatalad

##########################################
Managing your preprocessed data
##########################################

.. toctree::
   :maxdepth: 1
   :caption: Work with your BIDS derivatives to get ready for analysis.

   content_pages/04-01-fileFormats
   content_pages/04-02-templates
   content_pages/04-03-registration
   content_pages/04-04-visualization


##############################
Into the Wild West of analyses
##############################

.. toctree::
   :maxdepth: 1
   :caption: Tapping into the many ways in which to analyze fMRI data.

   content_pages/05-01-univariate
   content_pages/05-02-mvpa
   content_pages/05-03-surfaceBased
   content_pages/05-04-group
   content_pages/05-05-physiology

########
Appendix
########

.. toctree::
   :maxdepth: 1
   :caption: Haven't had enough? Some more information and resources.

   content_pages/06-01-tipsSplashPage
   content_pages/06-02-pygersWorkshops
   content_pages/06-03-usefulLicenses
   content_pages/06-04-contributing
   content_pages/06-05-glossary
   content_pages/06-06-resources
   content_pages/06-07-references

* :ref:`genindex`
* :ref:`search`

..
  stuff that we do not need or show at the moment

.. toctree::
   :hidden:

   website_info
   content_pages/website_info
   r

