##########################
Brand new to neuroimaging?
##########################

Familiarize yourself with important background reading material here. If you’re unsure about any terms, check out the `glossary <content_pages/glossary>`_.

.. toctree::
   :maxdepth: 1

   content_pages/01-01-openNeuro
   content_pages/01-02-whatIsBIDS
   content_pages/01-03-sampleProjectWithBIDS
   content_pages/01-04-sampleProjectWithDatalad
   content_pages/01-05-faq
   content_pages/01-06-designExp
   content_pages/01-07-overview

##########################
Setting up your experiment
##########################

.. toctree::
   :maxdepth: 1
   :caption: Follow these important steps before running your first subject!

   content_pages/02-01-reproin
   content_pages/02-02-prescan
   content_pages/02-03-forms


##########
Using BIDS
##########

.. toctree::
   :maxdepth: 1
   :caption: After running your first subject, go from raw DICOMs to preprocessed niftis. Make sure everything works before running more subjects!

   content_pages/03-01-converting
   content_pages/03-02-mriqc
   content_pages/03-03-fmriprep
   content_pages/03-04-fmriprepOutputs

##########################################
Managing your preprocessed data
##########################################

.. toctree::
   :maxdepth: 1
   :caption: Work with your BIDS derivatives to get ready for analysis.

   content_pages/04-01-fileFormats
   content_pages/04-02-templates
   content_pages/04-03-registration
   content_pages/04-04-visualization


##############################
Into the Wild West of analyses
##############################

.. toctree::
   :maxdepth: 1
   :caption: Tapping into the many ways in which to analyze fMRI data.

   content_pages/05-01-univariate
   content_pages/05-02-mvpa
   content_pages/05-03-surfaceBased
   content_pages/05-04-group
   content_pages/05-05-physiology

########
Appendix
########

.. toctree::
   :maxdepth: 1
   :caption: Haven't had enough? Some more information and resources.

   content_pages/06-01-tipsSplashPage
   content_pages/06-02-contributing
   content_pages/06-03-glossary
   content_pages/06-04-resources
   content_pages/06-05-references

* :ref:`genindex`
* :ref:`search`

..
  stuff that we do not need or show at the moment

.. toctree::
   :hidden:

   website_info
   content_pages/website_info
   content_pages/hack_pages/another-tip

