############
Introduction
############

.. toctree::
   :maxdepth: 1

   content_pages/01-01-howto
   content_pages/01-02-openNeuro
   content_pages/01-03-prereqs


##########################
Setting up your experiment
##########################

.. toctree::
   :maxdepth: 1

   content_pages/02-01-overview
   content_pages/02-02-environments
   content_pages/02-03-designExp
   content_pages/02-04-standardization



########
Appendix
########

.. toctree::
   :maxdepth: 1
   :caption: Further information and references

   glossary
   contributing
   content_pages/website_info


* :ref:`genindex`
* :ref:`search`

..
  stuff that we do not need or show at the moment

.. toctree::
   :hidden:

